// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMQnLSwRvc-vQ33U553W0a1esFQlccEY',
    appId: '1:960645673283:web:539c0ba9649de60057bff6',
    messagingSenderId: '960645673283',
    projectId: 'gym-zones',
    authDomain: 'gym-zones.firebaseapp.com',
    storageBucket: 'gym-zones.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMQnLSwRvc-vQ33U553W0a1esFQlccEY',
    appId: '1:960645673283:android:539c0ba9649de60057bff6',
    messagingSenderId: '960645673283',
    projectId: 'gym-zones',
    storageBucket: 'gym-zones.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIh07B6iLbPOVAWLAKFID38becDxKRKU',
    appId: '1:960645673283:ios:b591e616aaf13c3057bff6',
    messagingSenderId: '960645673283',
    projectId: 'gym-zones',
    storageBucket: 'gym-zones.appspot.com',
    iosBundleId: 'com.pixllmall.gymZones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQIh07B6iLbPOVAWLAKFID38becDxKRKU',
    appId: '1:960645673283:ios:b591e616aaf13c3057bff6',
    messagingSenderId: '960645673283',
    projectId: 'gym-zones',
    storageBucket: 'gym-zones.appspot.com',
    iosBundleId: 'com.pixllmall.gymZones',
  );
}
